apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: jovvix
  annotations:
    github.com/project-slug: backstage-itpl/jovvix
  links:
    - url: https://app.jovvix.com
      title: Quiz Platform
      icon: dashboard
      type: quiz-platform
spec:
  type: service
  lifecycle: production
  owner: guests
  providesApis:
    - jovvix-api

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: jovvix-api # A unique name for the API entity
  description: Jovvix REST API Docs
  tags:
    - rest
    - jovvix
spec:
  type: openapi
  lifecycle: production
  owner: guests
  definition:
    $text: ./api/assets/swagger.json
